version: '3'
services:
  main:
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    volumes:
      - ./:/var/www/html:cached
  builder:
    build:
      context: .
      dockerfile: ./etc/node/Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
